version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:2.17.0-pg16
    container_name: telemetry_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=telemetry_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - telemetry_net

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: telemetry_pgbouncer
    environment:
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=timescaledb
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - AUTH_TYPE=scram-sha-256
    ports:
      - "6432:5432"
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - telemetry_net

  grafana:
    image: grafana/grafana:10.4.1
    container_name: telemetry_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-ds.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - telemetry_net    

volumes:
  pgdata:
  grafana_data:

networks:
  telemetry_net:
    driver: bridge  
